name: portfolio
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  timeline_tile: ^2.0.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.4
  shared_preferences: ^2.2.0
  page_transition: ^2.0.9
  animated_splash_screen: ^1.3.0
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  permission_handler: ^10.4.3
  provider: ^6.0.5
  firebase_storage: ^11.2.6
  file_picker: ^5.5.0
  open_file: ^3.3.2
  easy_pdf_viewer: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/icons/
    - lib/assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
